### DISCUSSION TITLE
Visonic Event Log

### DISCUSSION THREAD

**Discussion by nikagl** [davesmeghead/visonic#192] [Q&A]
Hi all.

I am looking for a way to show my Visonic eventlog. Running "visonic.alarm_panel_eventlog" action against my entity works. It generates visonic_log_file.csv in my /config folder and after adding visonic_template.xml to my /config/templates folder it also generates visonic_log_file.xml.

After adding the debug entry (custom_components.visonic: debug) to my configuration.xml I noticed the debug lines contain the actual zone and event, where the csv/xml only contains a zone and event number.

For instance:
```
2025-05-30 00:09:02.623 DEBUG (MainThread) [custom_components.visonic.client] P0  Client: Sending HA Event visonic_alarm_panel_event_log_entry  {'panel': 0, 'panel_id': 'alarm_control_panel.visonic_alarm', 'current': 1, 'total': 250, 'date': '10/02/2025', 'time': '07:42:51', 'partition': '1', 'zone': 'Fob 06', 'event': 'Disarmed'}
```

Is changed to:
```
            <description>Partition 1,  Date 10/02/2025,  Time 07:42:51,  Current 1,  Zone 36,  Event 85</description>
```
and
```
current, total, partition, date, time, zone, event
1, 250, 1, 10/02/2025, 07:42:51, 36, 85
```

I haven't changed the template:
```
            <description>Partition {{entry.partition}},  Date {{entry.date}},  Time {{entry.time}},  Current {{entry.current}},  Zone {{entry.zone}},  Event {{entry.event}}</description>
```

Has someone configured a card to correctly show the eventlog with the actual zone/event information (like available in the log)? Or how can I get the actual zone/event matched to the zone/event numbers so I can try to create a card myself?

Kind Regards,

Nika.

**Comment by davesmeghead** [comment]
Hi,
I can look at adding the strings for zone and event in to the csv and xml files if that helps

**Comment by nikagl** [comment]
I'm trying to GPT myself out of this. Gemini helps pretty well, I have already created an automation that sends the log entries to an input_text helper. The helper is too small (max 255 chars) though and it overwrites the entries, so I'll need to figure out how to:

1. Send it to a logfile, sensor or attributes in a sensor instead
2. Display those in my card

Automation
``` 
alias: "Trigger: Visonic Store Readable Event Log"
description: ""
triggers:
  - event_type: visonic_alarm_panel_event_log_entry
    trigger: event
actions:
  - target:
      entity_id: input_text.visonic_event_log_display
    data:
      value: |
        {% set new_entry = '%s/%s | %s %s | P:%s | Zone: %s | Event: %s' % (
          trigger.event.data.current,
          trigger.event.data.total,
          trigger.event.data.date,
          trigger.event.data.time,
          trigger.event.data.partition,
          trigger.event.data.zone,
          trigger.event.data.event
        ) %} {% if trigger.event.data.current == 1 %}
          {{ new_entry }}
        {% else %}
          {{ states('input_text.visonic_event_log_display') + '\n' + new_entry }}
        {% endif %}
    action: input_text.set_value
```

Button card
```
type: grid
cards:
  - show_name: true
    show_icon: true
    type: button
    name: Refresh Visonic Event Log
    show_state: false
    tap_action:
      action: call-service
      service: visonic.alarm_panel_eventlog
      service_data:
        code: "0000"
        entity_id: alarm_control_panel.visonic_alarm
    icon: mdi:source-pull
```

Event Log display card
```
type: grid
cards:
  - type: markdown
    title: Visonic Panel Event Log
    content: |
      {{ states('input_text.visonic_event_log_display') }}
    grid_options:
      columns: full
      rows: 1
column_span: 4
```

**Comment by lygilygi** [comment]
I written small  UART debug log visible in ESP Home console if anyone is interested

`
uart:
  id: uart_bus_visonic
  baud_rate: 38400
  tx_pin: 1
  rx_pin: 3
  stop_bits: 1
  data_bits: 8
  parity: NONE
  debug:
    direction: BOTH
    after:
      delimiter: ""
    sequence:
      - lambda: |-
          char hex[5];
          std::string hex_str = "";
          for (auto b : bytes) {
            snprintf(hex, sizeof(hex), "%02X ", b);
            hex_str += hex;
          }
          std::string dir_str = (direction == esphome::uart::UART_DIRECTION_RX) ? "RX" : "TX";
          ESP_LOGI("uart_debug", "[%s] %s", dir_str.c_str(), hex_str.c_str());
`
<img width="1152" alt="Screenshot 2025-06-05 at 18 14 28" src="https://github.com/user-attachments/assets/383c2a45-d963-4320-8686-a163db93b16f" />

I don't know what is wrong with GitHub code  section - it is always broken 
<img width="776" alt="Screenshot 2025-06-05 at 18 17 16" src="https://github.com/user-attachments/assets/3521cabc-70a2-46bc-ad19-da762585235a" />

**Reply by nikagersonlohman** [reply]
I don't think this is related to this discussion topic?

**Comment by nikagl** [comment]
Still working on getting the event log to display. I changed the approach slightly though.

I've added this to my configuration.yaml so a sensor is added that listens to my visonic/event_log topic:
```
sensor:
  - platform: mqtt
    name: "Visonic Event Log"
    state_topic: "visonic/event_log"
```

This button triggers adding event log entries (replace 0000 for your code off course):
```
show_name: true
show_icon: true
type: button
name: Refresh Visonic Event Log
show_state: false
tap_action:
  action: call-service
  service: visonic.alarm_panel_eventlog
  service_data:
    code: "0000"
    entity_id: alarm_control_panel.visonic_alarm
icon: mdi:source-pull
```

This automation Publishes retained events to MQTT:
```
alias: "Trigger: Publish Visonic Event Log messages"
description: ""
triggers:
  - event_type: visonic_alarm_panel_event_log_entry
    trigger: event
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: "0"
      topic: >
        {{ 'visonic/event_log/event%03d' | format(trigger.event.data.current |
        int) }}
      payload: >-
        {{ '%s/%s | %s %s | P:%s | Zone: %s | Event: %s' |
        format(trigger.event.data.current,trigger.event.data.total,trigger.event.data.date,trigger.event.data.time,trigger.event.data.partition,trigger.event.data.zone,trigger.event.data.event)
        }}
      retain: true
mode: queued
```

This automation creates the sensors for these published events:
```
alias: "Trigger: Create Visonic Event Log Sensors via MQTT Discovery"
description: Creates sensors for each Visonic event log entry
triggers:
  - topic: visonic/event_log/#
    trigger: mqtt
actions:
  - data:
      topic: homeassistant/sensor/{{ trigger.topic.split("/")[-1] }}/config
      retain: true
      payload: |
        {
          "name": "Visonic Event {{ trigger.topic.split('event')[-1] }}",
          "state_topic": "{{ trigger.topic }}",
          "unique_id": "visonic_event_log_{{ trigger.topic.split('event')[-1] }}",
          "device": {
            "identifiers": ["visonic_event_log"],
            "name": "Visonic Event Log"
          }
        }
    action: mqtt.publish
mode: queued
```

And this markdown card shows these sensors:
```
type: markdown
title: Visonic Event Log
content: >
  {% for i in range(1, 251) %} - {{
  states('sensor.visonic_event_log_visonic_event_' ~ '{:03d}'.format(i)) }}

  {% endfor %}
grid_options:
  columns: full
  rows: auto
```

Next to be done is better card formatting however this already displays the event log quite well :)

Looking forward to some feedback...

Regards,

Nika.
