### ISSUE TITLE
Continual connects & disconnects

### ISSUE THREAD

**Issue by mechanimal82** [davesmeghead/visonic#163]
So for a month or so - I know, should have mentioned this earlier - Visonic seems to continually lose connection, and then restart... this cycle seems to happen every 10 minutes or so. As far as I can tell the Wemos is connected and ESP is not showing any disconnect - I can still toggle the switches on and off, and my router is not showing the connection drop. So I'm unsure what could be causing it.

I've enabled debug logging and captured the full logs here:

https://drive.google.com/file/d/1rnjZaIJURBeF2RFWG2lAgZ4J9uIvvAJK/view?usp=sharing

I'm sure it's a PICNIC issue, but have tried resolving myself with no joy. Any help would be appreciated!

**Comment by davesmeghead** [comment]
Hi,
I've just had a look at the log file and a couple of things point to one of your automations ...... maybe

First of all this in your log file
```
2024-10-11 17:05:07.301 DEBUG (MainThread) [custom_components.visonic] ************* terminating connection **************
```
This is the 1st occurrence of many.  
This is the 1st line of the function `async_unload_entry` that HA calls to unload the integration, potentially also restarting it.  So I'm fairly certain that it's not your connection to the ESP that's failing.

It also means that something in HA is either stopping or stopping/restarting the integration, especially if you look through all the entries in the log file of the above they're approx every minute or so (17:05:07.301 then 17:06:07.356 etc).

Secondly, I spotted this among the errors
```
Template<template=({{ state_attr('alarm_control_panel.visonic_alarm', 'Exception Count') | int }}) renders=2>
```
This is where I have a confession, I changed "Exception Count" to "Disconnection Count" and I've not updated the Wiki. Are you using this in an Automation to restart the integration?  They're not exceptions you see, they're disconnections for any reason and not just exceptions.

Dave

**Comment by davesmeghead** [comment]
I've cheated :smirk: and just updated the Wiki, it now states 'Disconnection Count'

**Comment by mechanimal82** [comment]
Thanks Dave. I've updated the template to look for disconnections instead.
I did wonder why that automation hadn't activated in such a long time given
all these disconnects 🤣

So something is unloading async, but not sure what... I'll go hunting!

**Comment by mechanimal82** [comment]
Found it.... I had a node red automation polling the panel status every minute. I had template sensors which have changed name... So not just the 'Disconnection Count', things like 'Panel Mode' are now just 'Mode'. So I need to update these to reflect the new names.

I think I found these somewhere in the wiki or in the repo

```
  - platform: template
    scan_interval: 5
    sensors:
        visonic_exception_count:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Disconnection Count') | int }}
          friendly_name: 'Panel Disconnection Count' 
        visonic_panel_status:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Status') | title  }}
          friendly_name: 'Panel Status' 
        visonic_panel_mode:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Mode') | title  }}
          friendly_name: 'Panel Mode' 
        visonic_panel_last_event:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Last Event') | title | replace("/", "by") | replace("  ", " ") | trim | replace("Fob 01", "Dan")  | replace("Fob 02", "Spare") | replace("Fob 03", "Wife") | replace("User 01", "Your Phone") }}
          friendly_name: 'Last Event' 
        visonic_panel_alert_in_memory:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Alert In Memory') | title  }}
          friendly_name: 'Panel Alert In Memory' 
        visonic_panel_trouble:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Trouble') | title  }}
          friendly_name: 'Panel Trouble' 
        visonic_siren_active:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Siren Active') == "Yes"}}
          friendly_name: 'Siren' 
        visonic_panel_ready:
          value_template: >-
                      {{ state_attr('alarm_control_panel.visonic_alarm', 'Panel Ready') == "Yes" }}
          friendly_name: 'Panel Ready'
```
