### ISSUE TITLE
Only standard mode with new release

### ISSUE THREAD

**Issue by rafa67** [davesmeghead/visonic#18]
Hi
I was using this component without any issue for a long time.
My previous version 0.3.5.3 was working in powerlink mode without any issue.
This is the information of the panel entity with this version:
**_code_format: null
changed_by: null
code_arm_required: true
PluginVersion: 0.3.5.3
Comm Exception Count: 0
Mode: Powerlink
Watchdog Timeout: 0
Download Timeout: 0
Panel Last Event: Exit Installer / System
Panel Alarm Status: None
Panel Trouble Status: None
Panel Siren Active: No
Panel Status: Disarmed
Panel Status Code: 0
Panel Ready: Yes
Panel Alert In Memory: No
Panel Trouble: No
Panel Bypass: No
Panel Status Changed: No
Panel Alarm Event: No
Panel Armed: No
Power Master: No
Model: PowerMax Pro Part
Model Type: 87
Panel Name: Unknown
Set Voice Option: Enable Voice
Auto Arm Option: Disable
Auto Arm Time: 12:00
Squawk Option: Disable
Time Format: Europe - 24H
Date Format: Europe DD/MM/YYYY
Entry Delay 1: 15 Seconds
Entry Delay 2: 15 Seconds
Exit Delay: 60 Seconds
Bell Time: 1 Minute
Abort Time: None
Alarm Cancel Time: 5 Minutes
Quick Arm: Off
Bypass: No Bypass
Exit Mode: Normal
Piezo Beeps: Disable
Trouble Beeps: Disable
Panic Alarm: Audible Panic
Swinger Stop: After 1 Time
Cross Zoning: Off
Supevision Interval: 12 Hours
Not Ready: Normal
Auxiliary Keyfob Button function 1: System Status
Auxiliary Keyfob Button function 2: System Status
Jamming Detection: Disable
Latchkey Arming: Off
No Activity Time: Disable
Back Light Time: Off After 10 Seconds
Duress: 2580
Piezo Siren: Off
Reset Option: User Reset
Tamper Option: Off
Siren On Line: Disable on Fail
Memory Prompt: Enable
Disarm Option: Any Time
Bell Report Option: Others
Low Battery Acknowledge: Off
Screen Saver: Off
Confirm Alarm Timer: 60 Minutes
AC Failure Report: 5 Minutes
User Permit: Disable
Autotest Time: 12:00
Autotest Cycle: Disable
1st Central Station (CNTR) Tel. No.: fxxxxf
2nd Central Station (CNTR) Tel. No.: fxxxxf
1st Account No: 000083
2nd Account No: 000083
Report Format: 5
4/2 Pulse Rate: 20 pps
Report to Central Station: Disable
Report Confirmed Alarm: Disable Report
Send 2wv Code: Don't Send
Two-Way Voice To Central Stations: Disable
Ringback Time: 1 Minute
Central Station Dialing Attempts: 8
1st Ringback Tel No: xxxxf
2nd Ringback Tel No: xxxxf
Two-Way Voice - Private Phones: Enable
Reporting To Private Tel: All but Open/Close
Report To Pager: Disable Report
Recent Close Report: Off
Remote Access: On
Zone Restore: Report Restore
Upload Option: Any Time
Dialing Method: Tone (DTMF)
Line Failure Report: Immediately
System Inactive Report: Disable
Ambient Level: Low Level
GSM Install: Not Installed
GSM Report to SMS: Disable Report
GSM Line Failure: Don't Report
GSM Line Purpose: SMS Only
GSM Select Antenna: Internal antenna
PowerLink Failure: Disable Report
PGM Pulse Time: 2 Seconds
PGM By Arm Away: Turn Off
PGM By Arm Home: Turn Off
PGM By Disarm: Turn On
PGM By Memory: Disable
PGM By Delay: Turn Off
PGM By Keyfob: Disable
PGM By Line Fail: No
PGM Act Zone A: Disable
PGM Act Zone B: Disable
PGM Act Zone C: Disable
Internal/Strobe Siren: Strobe
X10 House Code: B
X10 Flash On Alarm: No Flash
X10 Trouble Indication: Disable
X10 Report on Fail to Central Station 1: Disable
X10 Report on Fail to Central Station 2: Disable
X10 Report on Fail to Pager: Disable
X10 Report on Fail to Private: Disable
X10 Report on Fail to SMS: Disable
X10 Lockout Time (start HH:MM): 00:00
X10 3 Phase and frequency: Disable
Panel Serial: 2113008287.
Panel Eprom: J-701629 C17.115
Panel Software: JS702317 C17.108
Door Zones: Z29
Motion Zones: Z01,Z11,Z12,Z15
Smoke Zones: 
Other Zones: 
Devices: PGM,X01,X02,X10,K100
friendly_name: Visonic Alarm
supported_features: 3_**

I have tried to update the component to the 0.4.2.0 version and it seems that is only possible to connect in standard mode. I tried the full restart sequence for powerlink without success. The panel is PowerMax Pro Part type 87.

In the following link you can find the log file with the result for the 0.4.2.0 version.
[https://drive.google.com/file/d/1wPqt9flh1YFrt8xEUpiKZdvCuFmf3KCv/view?usp=sharing](url)

Can you verify is there are something wrong?
Thank you very much for your suport

**Comment by davesmeghead** [comment]
Your panel is sending out the same message over and over again, this happens when you bombard your panel with home assistant restarts in a row. I believe that the panel sees this as an attack and resists any kind of connection.  The best thing to do in this situation is to leave it for 30 to 60 minutes and try again.  Either stop home assistant or disable/delete the visonic integration.

**Comment by rafa67** [comment]
I stopped home assistant for more than one hour and I restarted with the same behaviour.
This is my configuration that works perfectly with the 0.3.5.3 version

 **_visonic:
  device:
    type: ethernet
    host: '192.168.1.52'
    port: 23
  motion_off: 120
  language: 'EN'
  force_standard: 'no'
  sync_time: 'yes'
  allow_remote_arm: 'yes'
  allow_remote_disarm: 'yes'
  override_code: '0942'
  arm_without_usercode: 'no'_**

Is it ok?

**Comment by davesmeghead** [comment]
Hi,
Are you running the latest home assistant?  version 0.110.1

The component is reading in the parameters from the configuration.yaml incorrectly and I'm not sure why.  You can try 2 things, first replace your parameter set with mine

```
visonic:
  device:
    type: ethernet
    host: '192.168.1.52'
    port: 23
  motion_off: 60
  language: 'EN'
  force_standard: 'no'
  sync_time: 'yes'
  allow_sensor_bypass: 'yes'
  exclude_x10: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15'
#  exclude_sensor: '2,3'
  allow_remote_arm: 'yes'
  allow_remote_disarm: 'yes'
  b0_enable_motion_processing: 'no'
  b0_min_time_between_triggers: 30
  b0_max_time_for_trigger_event: 5
  panellog_logentry_event: 'yes'
  panellog_csv_add_title_row: 'yes'
  panellog_xml_filename: 'panel_log.xml'
  panellog_csv_filename: 'panel_log.csv'
  panellog_complete_event: 'yes'
  panellog_reverse_order: 'yes'
  panellog_max_entries: 10
  siren_sounding: ["intruder", "panic"]
```

Make sure there's no integration loaded in home assistant. In the frontend integrations page, select the 3 vertical dots and delete the integration (it it's there). Restart home assistant.

Did that work?

If that doesn't work then delete the integration again. This time add it as an integration from within HA, select the big + button (bottom right) and add "visonic intruder alarm" from the list.
