### ISSUE TITLE
alarm_sensor_bypass service call appears to have broken

### ISSUE THREAD

**Issue by stridger** [davesmeghead/visonic#55]
I am using the visonic.alarm_sensor_bypass HA service call in some of my scrips, which worked fine so far, but since recently it seems to have broken. I am not sure if that is due to a module or a HA update.

It logs "Attempt to bypass sensor but entity not defined", even though the entity clearly is defined. The callI use is as follows:

```
service: visonic.alarm_sensor_bypass
data:
  entity_id: binary_sensor.visonic_z02
  bypass: true
```

the entity does exist and bypassing works fine from the new frontend switch, but it would be good to be able to use the service call again.

Any clues?

Thank you so much for all your work on this, this integration is quite key for my alarm panel automations but also home automations more generally as it exposes all Powermax sensors to HA.
