### ISSUE TITLE
Powermaster 30 PIR motion

### ISSUE THREAD

**Issue by pbathuk** [davesmeghead/visonic#72]
Hi, hopefully this is the correct location to ask this question... 
I have a powermaster 30 with the ethernet usr-tcp232-e2 that has been running for a number of years now. 
I have all pirs set to always alert and if I look at the panel they come up as "PIR X violated"... Or something similar.

However in HA unless the panel is armed they don't work as I expect, i.e. the sensor does not show as occupied / motion detected. 

Is this a known issue or am I missing a setting.
I am on the latest HACS version, with the current state showing:

```yaml
code_format: null
changed_by: User 01
code_arm_required: true
Panel Mode: Powerlink
Protocol Version: 1.0.17.2
Watchdog Timeout (Total): 0
Watchdog Timeout (Past 24 Hours): 0
Download Timeout: 0
Download Retries: 0
Panel Problem Count: 0
Panel Problem Time: ''
Panel Last Event: Disarm / User 01
Panel Last Event Data:
  Zone: 0
  Entity: null
  Tamper: false
  Siren: false
  Reset: false
  Time: '2023-02-23T08:19:22.743759'
  Count: 1
  Type:
    - 85
  Event:
    - 97
  Mode:
    - Disarm
  Name:
    - User 01
Panel Alarm Status: None
Panel Trouble Status: None
Panel Siren Active: false
Panel Status: Disarmed
Panel Status Code: Disarmed
Panel Ready: 'Yes'
Panel Alert In Memory: 'No'
Panel Trouble: 'No'
Panel Bypass: 'No'
Panel Status Changed: 'No'
Panel Alarm Event: 'No'
Panel Armed: 'No'
Power Master: 'Yes'
Panel Model: PowerMaster 30
Panel Type: 8
Model Type: 53
Panel Name: Unknown
Set Voice Option: Disable Voice
Auto Arm Option: Disable
Auto Arm Time: '12:00'
Squawk Option: Disable
Time Format: Europe - 24H
Date Format: Europe DD/MM/YYYY
Entry Delay 1: 30 Seconds
Entry Delay 2: 1 Minute
Exit Delay: 30 Seconds
Bell Time: 10 Minutes
Abort Time: None
Alarm Cancel Time: 5 Minutes
Quick Arm: 'On'
Bypass: No Bypass
Exit Mode: Normal
Piezo Beeps: Off when Home
Trouble Beeps: Off at Night
Panic Alarm: Audible Panic
Swinger Stop: After 2 Times
Cross Zoning: 'Off'
Supevision Interval: 1 Hour
Not Ready: Normal
Auxiliary Keyfob Button function 1: Instant Arm
Auxiliary Keyfob Button function 2: Instant Arm
Jamming Detection: EN 30/60
Latchkey Arming: 'On'
No Activity Time: Disable
Back Light Time: Off After 10 Seconds
Duress: '0000'
Piezo Siren: 'On'
Reset Option: User Reset
Tamper Option: 'Off'
Siren On Line: Disable on Fail
Memory Prompt: Enable
Disarm Option: Any Time
Bell Report Option: EN Standard
Low Battery Acknowledge: 'On'
Screen Saver: Reset By Code
Confirm Alarm Timer: 30 Minutes
AC Failure Report: 180 Minutes
User Permit: Enable
Autotest Time: '03:44'
Autotest Cycle: Disable
1st Account No: 
2nd Account No: 
Report Format: Contact ID
4/2 Pulse Rate: 20 pps
Report to Central Station: Disable
Report Confirmed Alarm: Disable Report
Send 2wv Code: Don't Send
Two-Way Voice To Central Stations: Disable
Ringback Time: 1 Minute
Central Station Dialing Attempts: '8'
Two-Way Voice - Private Phones: Enable
Reporting To Private Tel: Disable Report
Report To Pager: Disable Report
Recent Close Report: 'Off'
Remote Access: 'On'
Zone Restore: Don't Report
Upload Option: Any Time
Dialing Method: Tone (DTMF)
Line Failure Report: Immediately
System Inactive Report: Disable
Ambient Level: Low Level
GSM Install: Not Installed
GSM Report to SMS: Disable Report
GSM Line Failure: 5 Minutes
GSM Line Purpose: SMS Only
GSM Select Antenna: Internal antenna
PowerLink Failure: Disable Report
PGM Pulse Time: 2 Seconds
PGM By Arm Away: Disable
PGM By Arm Home: Disable
PGM By Disarm: Disable
PGM By Memory: Disable
PGM By Delay: Disable
PGM By Keyfob: Disable
PGM By Line Fail: 'No'
PGM Act Zone A: Disable
PGM Act Zone B: Disable
PGM Act Zone C: Disable
Internal/Strobe Siren: Internal Siren
X10 House Code: B
X10 Flash On Alarm: No Flash
X10 Trouble Indication: Disable
X10 Report on Fail to Central Station 1: Disable
X10 Report on Fail to Central Station 2: Disable
X10 Report on Fail to Pager: Disable
X10 Report on Fail to Private: Disable
X10 Report on Fail to SMS: Disable
X10 Lockout Time (start HH:MM): '07:00'
X10 3 Phase and frequency: Disable
Panel Serial: 
Panel Eprom: J-701248 K17.131
Panel Software: JS702505 K17.131
Door Zones: Z01,Z04
Motion Zones: Z02,Z03,Z05,Z06
Smoke Zones: ''
Other Zones: ''
Devices: S00
Client Version: 0.8.2.4
Exception Count: 0
panel: 0
friendly_name: Visonic Alarm
supported_features: 7

```

Happy to share other information if that helps, but hoping it is user error.
