### ISSUE TITLE
Way to obtain and use zone names

### ISSUE THREAD

**Issue by ambhargava** [davesmeghead/visonic#91]
Hi, I am happily using this integration for my Visonic pro. Thank you for making it  and sharing.

One question I had is if it's possible to fetch the zone names from visonic and use that to name the sensors in home assistant? 

Also, once I have manually named them in home assistant but looks like that got overwritten on reload.

Thanks
Amit

**Comment by davesmeghead** [comment]
Hi,
I've noticed that as well, I'm not sure yet if it's my integration or a change in Home Assistant.
While I investigate you can still use the "old way" of doing this by putting this in your configuration.yaml
```
homeassistant:
  customize:
    # Add an entry for each entity that you want to overwrite.
    binary_sensor.visonic_z01:
      friendly_name: Wibble
    binary_sensor.visonic_z02:
      friendly_name: Wobble
```
Thanks
